const API='https://hanzuvpn-bot-production.up.railway.app';
const tg=window.Telegram?.WebApp;
const FALLBACK_PLANS=[{volume:'1',price:3500,available:true},{volume:'10',price:35000,available:true},{volume:'15',price:52500,available:true},{volume:'20',price:70000,available:true},{volume:'30',price:105000,available:true},{volume:'40',price:140000,available:true},{volume:'50',price:175000,available:true},{volume:'100',price:350000,available:true}];
let data={balance:0,plans:FALLBACK_PLANS,services:[],card:'',min_charge:10000}; let pending=null;
function headers(){return {'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''}}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',3000)}
function money(n){return Number(n||0).toLocaleString('fa-IR')}
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===id))}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>page(x.dataset.page));document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>page(x.dataset.go));document.getElementById('close').onclick=()=>document.getElementById('modal').classList.add('hidden');
function renderPlans(){const plans=data.plans?.length?data.plans:FALLBACK_PLANS;document.getElementById('plans').innerHTML=plans.map(p=>`<div class="plan"><h3>${p.volume} گیگ</h3><strong>${money(p.price)} تومان</strong><span class="${p.available===false?'unavailable':'available'}">${p.available===false?'● ناموجود':'● خرید'}</span><button class="primary" style="margin-top:12px" onclick="buy('${p.volume}',${p.price})">خرید</button></div>`).join('')}
function render(){document.getElementById('balance').textContent=money(data.balance);document.getElementById('balance2').textContent=money(data.balance)+' تومان';renderPlans();document.getElementById('servicesList').innerHTML=data.services?.length?data.services.map(s=>`<div class="service"><h3>📦 ${s.volume} گیگ</h3><p>انقضا: ${s.expires_at||'-'}</p><p><a href="${s.link||'#'}" target="_blank">${s.link||'لینک موجود نیست'}</a></p><button class="primary" onclick="renew(${s.id})">🔄 تمدید ${money(Number(s.volume)*3500)} تومان</button></div>`).join(''):'<div class="card">هنوز سرویس فعالی نداری.</div>'}
async function load(){if(tg){tg.ready();tg.expand()}renderPlans();if(!tg?.initData){toast('لطفاً Mini App را از داخل ربات باز کن');return}try{const r=await api('/api/bootstrap');if(!r.ok)throw Error(r.error||'خطای سرور');data={...data,...r,plans:r.plans?.length?r.plans:FALLBACK_PLANS};document.getElementById('hello').textContent='سلام '+(r.user?.first_name||'دوست من')+' 👋';render()}catch(e){render();toast('پلن‌ها نمایش داده شدند؛ اتصال سرور برقرار نیست')}}
async function buy(volume,price){if(Number(data.balance)>=price){if(!confirm(`خرید ${volume} گیگ به مبلغ ${money(price)} تومان؟`))return;try{const r=await api('/api/buy',{method:'POST',body:JSON.stringify({volume})});if(r.ok){toast('خرید موفق شد 🎉');await load();page('services')}else if(r.error==='insufficient_balance'){pending={type:'buy',volume,price};openReceipt(`خرید ${volume} گیگ`,price)}else if(r.error==='no_stock'){toast('این حجم فعلاً موجود نیست')}else toast('خرید انجام نشد')}catch(e){toast('ارتباط با سرور برقرار نشد')}}else{pending={type:'buy',volume,price};openReceipt(`خرید ${volume} گیگ`,price)}}
function openReceipt(title,amount){document.getElementById('modalTitle').textContent=title;const card=data.card?`<br><br>💳 شماره کارت:<br><b>${data.card}</b>`:'';document.getElementById('modalText').innerHTML=`مبلغ: <b>${money(amount)} تومان</b><br>مبلغ را واریز کن و تصویر رسید را انتخاب کن.${card}`;document.getElementById('modal').classList.remove('hidden')}
async function renew(id){try{const r=await api('/api/renew',{method:'POST',body:JSON.stringify({order_id:id})});if(r.ok){toast('تمدید با موفقیت انجام شد 🎉');await load()}else if(r.error==='insufficient_balance'){toast('موجودی کیف پول کافی نیست')}else toast('تمدید انجام نشد')}catch(e){toast('ارتباط با سرور برقرار نشد')}}
document.getElementById('receiptBtn').onclick=async()=>{const f=document.getElementById('receipt').files[0];if(!f||!pending){toast('تصویر رسید را انتخاب کن');return}const reader=new FileReader();reader.onload=async()=>{try{let endpoint,body;if(pending.type==='buy'){endpoint='/api/buy-receipt';body={volume:pending.volume,image:reader.result}}else{endpoint='/api/charge-receipt';body={amount:pending.amount,image:reader.result}}const r=await api(endpoint,{method:'POST',body:JSON.stringify(body)});if(r.ok){document.getElementById('modal').classList.add('hidden');toast('رسید ارسال شد؛ منتظر تأیید مدیریت باش');pending=null;document.getElementById('receipt').value=''}else toast('ارسال رسید ناموفق بود')}catch(e){toast('ارتباط با سرور برقرار نشد')}};reader.readAsDataURL(f)};
document.getElementById('chargeBtn').onclick=()=>{const amount=Number(document.getElementById('chargeAmount').value);if(amount<10000){toast('حداقل شارژ ۱۰٬۰۰۰ تومان است');return}pending={type:'charge',amount};openReceipt('شارژ کیف پول',amount)};load();
